# Generated by Django 6.1.1 on 2026-09-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leaderboard_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
