# Generated by Django 6.1.1 on 2026-09-18 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_initial_sets(apps, schema_editor):
    ClimbSet = apps.get_model('climbs', 'ClimbSet')
    Climb = apps.get_model('climbs', 'Climb')
    for wall, label in (('main', 'Main Wall — current set'),
                        ('cave', 'Cave — current set')):
        climb_set, _ = ClimbSet.objects.get_or_create(
            wall=wall, is_active=True, defaults={'label': label})
        Climb.objects.filter(wall=wall, climb_set__isnull=True).update(
            climb_set=climb_set)


def unseed_initial_sets(apps, schema_editor):
    ClimbSet = apps.get_model('climbs', 'ClimbSet')
    ClimbSet.objects.filter(label__endswith='— current set').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall', models.CharField(choices=[('main', 'Main Wall'), ('cave', 'The Cave')], max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ascent',
            unique_together={('user', 'climb')},
        ),
        migrations.AddField(
            model_name='climb',
            name='climb_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climbs', to='climbs.climbset'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='climbs.climb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(seed_initial_sets, unseed_initial_sets),
    ]
