# Generated by Django 6.1.1 on 2026-09-18 12:31

from django.db import migrations, models


def backfill_tags(apps, schema_editor):
    """Keep every existing climb's colour: seed the new tag from the
    old grade-derived bands (V0 white, V1 black, V2-V3 red, V4 green,
    V5 blue, V6 yellow, V7 orange, V8+ project, unknown mystery)."""
    Climb = apps.get_model('climbs', 'Climb')
    for climb in Climb.objects.all():
        try:
            number = int(str(climb.grade).lstrip('Vv'))
        except (TypeError, ValueError):
            number = None
        if number is None:
            tag = 'mystery'
        elif number <= 0:
            tag = 'white'
        elif number <= 1:
            tag = 'black'
        elif number <= 3:
            tag = 'red'
        elif number <= 4:
            tag = 'green'
        elif number <= 5:
            tag = 'blue'
        elif number <= 6:
            tag = 'yellow'
        elif number <= 7:
            tag = 'orange'
        else:
            tag = 'project'
        if climb.tag != tag:
            climb.tag = tag
            climb.save(update_fields=['tag'])


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0002_climbset_alter_ascent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climb',
            name='tag',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('project', 'Project'), ('mystery', 'Mystery')], default='white', max_length=10),
        ),
        migrations.RunPython(backfill_tags, migrations.RunPython.noop),
    ]
