# Generated by Django 6.1.1 on 2026-09-20 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0004_newspost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ascent',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ascent',
            name='void_reason',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.CreateModel(
            name='AscentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'create'), ('edit', 'edit'), ('delete', 'delete'), ('void', 'void'), ('unvoid', 'unvoid')], max_length=10)),
                ('old_tries', models.PositiveIntegerField(blank=True, null=True)),
                ('new_tries', models.PositiveIntegerField(blank=True, null=True)),
                ('old_grade', models.CharField(blank=True, default='', max_length=5)),
                ('new_grade', models.CharField(blank=True, default='', max_length=5)),
                ('old_points', models.PositiveIntegerField(blank=True, null=True)),
                ('new_points', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ascent_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('ascent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='climbs.ascent')),
                ('climb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ascent_audits', to='climbs.climb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ascent_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=10)),
                ('points', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('reviewed', 'reviewed'), ('dismissed', 'dismissed'), ('confirmed', 'confirmed')], default='open', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('ascent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='climbs.ascent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('details', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
